### ISSUE TITLE
Why not use prototype?

### ISSUE THREAD

**Issue by gonutz** [baumhoto/GoRampage#1]
Hey there, I am the author of the github.com/gonutz/prototype library. I saw that you considered it for your tutorial series. Thanks, that is really cool. I just wanted to know what was missing for you to be able to use it as you wanted?

I had taken a look at your fork before you removed it, did you want to fill a buffer of pixels and render it to the screen?

**Comment by baumhoto** [comment]
Hey gonutz, yes the tutorial series is about implementing an Wolfenstein 3D like raycaster, thus setting each pixel explicitly and then dump the output to the screen. 

I modified your library that it would me allow to just pass it an image and render this to the screen using the DrawTexture logic ( (bypassing the texture cache, of course). Everything worked fine  but later i recognized an ever increasing ram usage with my change. 300 to 500 MB every 10 seconds thus after a few minutes it was using 10 GB or more. 

I check my code for memory leaks,  but i couldn't find any thus my assumption was that somewhere in the render code the memory for the rendered image was not freed? (just guessing here, but ram-usage was increasing really fast and rendering an image 60 times a seconds might explain that)

I didn't want to go down that rabbit hole to figure out what the problem might be, just learning Go and platform specific render-code is not the best to start tinkering with. So i decided to look for a library which would allow me to do that.

**Comment by gonutz** [comment]
Alright, thanks for the feedback. I think in the near future I will add support for this kind of thing - dynamic images that is.

I don't know why your RAM usage grew, I would have expected an increase in VRAM. On Windows the textures are stored in video memory and never freed if you do not call d3d9.Texture.Release explicitely. That might have been the problem.

On the other platforms the library uses SDL2 and GLFW and I don't know how they handle this. It might be that when you create a new texture there it is stored in RAM.

I have had use cases like this in the past, where I wanted to draw to the screen in software. This might be a good time to add something like this to the library :-)
